version: "2.1"
services:
  bundesliga:
    image: lukasdotcom/bundesliga:development
    container_name: bundesliga
    links:
      - db
    environment:
      - ENABLE_EPL=enabled
      - NEXTAUTH_URL=http://localhost # The url of the server
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bundesliga
      - MIN_UPDATE_TIME=120 # Minimum amount of seconds to pass before the data updates on Fri, Sat, and Sun to prevent spamming the api.
      - MIN_UPDATE_TIME_TRANSFER=3600 # Minimum amount of seconds to pass before the data is updated during the transfer period
      # Get your oauth details for sign in with google or github and fill it in below(not required)
      #- GOOGLE_ID=
      #- GOOGLE_SECRET=
      #- GITHUB_ID=
      #- GITHUB_SECRET=
      - NEXTAUTH_SECRET=hkf9eUXAZKjw99/hZ4Rrw7aNe47qxB+QuojMwmxbFqA= # If you want to change this run openssl rand -base64 32 and plug the result into this
      - BCRYPT_ROUNDS=9 # The number of rounds the password should be hashed
    ports:
      - 80:3000
    restart: always
    volumes:
      - /locationToWhereThisGithubIsDownloaded:/app
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bundesliga
    restart: always
volumes:
  bundesliga:
    external: true
