version: "2.1"
services:
  bundesliga:
    image: lukasdotcom/bundesliga:development
    container_name: bundesliga
    links:
      - db
    environment:
      # To see a list of the enviromental variables and what should get changed look at the env.md file located at https://github.com/Lukasdotcom/fantasy-manager/blob/main/ENV.md.
      - NEXTAUTH_URL=http://localhost # The url of the server
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bundesliga
      - MIN_UPDATE_TIME=120
      - MIN_UPDATE_TIME_TRANSFER=3600
      - NEXTAUTH_SECRET=
      - APP_ENV=development
      - NODE_ENV=development
    ports:
      - 80:3000
    restart: always
    volumes:
      - /locationToWhereThisRepoIsDownloaded:/app
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bundesliga
    restart: always
volumes:
  bundesliga:
    external: true
