version: "2.1"
services:
  bundesliga:
    image: lukasdotcom/fantasy-manager:1 # Change 1 to nightly if you want to be using the bleeding edge and latest if you want the last stable release. Major versions may have trouble between upgrades read the release before upping the major version.
    container_name: bundesliga
    links:
      - db
    environment:
      - NEXTAUTH_URL=http://localhost # The url of the server
      - SQLITE=/mnt/bundesliga.db
      - MIN_UPDATE_TIME=120 # Minimum amount of seconds to pass before the data updates on Fri, Sat, and Sun to prevent spamming the api.
      - MIN_UPDATE_TIME_TRANSFER=3600 # Minimum amount of seconds to pass before the data is updated during the transfer period
      # Look at the leagues.md file for steps to enable every league
      #- ENABLE_EPL=enabled # Uncomment this to enable the premier league
      # Get your oauth details for sign in with google or github and fill it in below(not required)
      #- GOOGLE_ID=
      #- GOOGLE_SECRET=
      #- GITHUB_ID=
      #- GITHUB_SECRET=
      - NEXTAUTH_SECRET= # run openssl rand -base64 32 and plug the result into this
      - BCRYPT_ROUNDS=9 # The number of rounds the password should be hashed
      # The admin user is whatever id is given, and the count starts at 1
      - ADMIN=1
      - DOWNLOAD_PICTURE=needed # This is the setting to decide if player pictures should be downloaded to disk.  No means that they will never be downloaded to disk, needed means they will be downloaded when needed, and yes means they will be downloaded when a new picture is discovered. The default is needed.
    ports:
      - 80:3000
    restart: always
    volumes:
      - bundesliga:/mnt
    # Uncomment the following if you want the downloaded pictures to persist between updates. Leave this commented if you set DOWNLOAD_PICTURE to no. If you set DOWNLOAD_PICTURE to yes you should uncomment it.
    #  - pictures:/app/players
volumes:
  bundesliga:
    external: true
  #pictures:
  #  external: true
