version: "2.1"
services:
  bundesliga:
    image: lukasdotcom/fantasy-manager:1 # Change 1 to latest if you want the last stable release. Major versions may have trouble between upgrades read the release before any update.
    container_name: bundesliga
    links:
      - db
    environment:
      # To see a list of the enviromental variables and what should get changed look at the env.md file located at https://github.com/Lukasdotcom/fantasy-manager/blob/main/ENV.md.
      - NEXTAUTH_URL=http://localhost # The url of the server
      - NEXTAUTH_SECRET= # run openssl rand -base64 32 and plug the result into this
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bundesliga
      - ADMIN=1
    ports:
      - 80:3000
    restart: always
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bundesliga
    restart: always
    volumes:
      - bundesliga:/var/lib/mysql
    # Uncomment the following if you want the downloaded pictures to persist between updates. Leave this commented if you set DOWNLOAD_PICTURE to no. If you set DOWNLOAD_PICTURE to yes you should uncomment it.
    #  - pictures:/app/players
volumes:
  bundesliga:
    external: true
  #pictures:
  #  external: true
